Assignment/Assignment/Assignment/Controllers/AppCalendarController.cs
using Assignment.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace Assignment.Controllers
{
    public class AppCalendarController : Controller
    {
        private Model2 db = new Model2();
        // GET: AppCalendar
        public ActionResult Index()
        {
            var types = db.ServiceType.ToList();
            //List<SelectListItem> selects = new List<SelectListItem>();
            //foreach (var t in types)
            //{
            //    selects.Add(new SelectListItem() { Value=t.TypeId.ToString(), Text=t.TypeName});

            //}

            ViewBag.Selections = types;
            return View();
        }

        public ActionResult AdminIndex()
        {
            var types = db.ServiceType.ToList();
            var context = new IdentityDbContext();
            var users = context.Users.ToList();
            ViewBag.Us = users;
            //List<SelectListItem> selects = new List<SelectListItem>();
            //foreach (var t in types)
            //{
            //    selects.Add(new SelectListItem() { Value=t.TypeId.ToString(), Text=t.TypeName});

            //}

            ViewBag.Selections = types;
            return View();
        }

        [HttpGet]
        public JsonResult GetEvents()
        {

            var userId = User.Identity.GetUserId();
            var events = db.Appointment.Where(a => a.UID == userId).Include(a => a.ServiceType).ToList();
            var context = new IdentityDbContext();
            if (User.IsInRole("Admin"))
            {
                events = db.Appointment.Include(a => a.ServiceType).ToList();
                foreach (var e in events)
                {
                    var id = e.UID;
                    var user = context.Users.Where(s => s.Id == id).FirstOrDefault();
                    e.UID = user.Email;
                }
            }

            //var events = db.Appointment.ToList();

            //Console.WriteLine(events.Count());



            return new JsonResult { Data = events, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        [HttpPost]
        public JsonResult SaveEvent(Appointment e)
        {
            var status = false;
            var ser = db.ServiceType.Where(s => s.TypeId == e.TypeId).FirstOrDefault();
            if (e.AppId > 0)
            {
                var v = db.Appointment.Where(a => a.AppId == e.AppId).FirstOrDefault();
                
                if (v != null)
                {
                    v.AppDate = e.AppDate;
                    v.AppAddress = e.AppAddress;
                    v.TypeId = e.TypeId;
                    v.ServiceType = ser;
        
                }
            }
            else
            {
                var existApp = db.Appointment.Where(a => DbFunctions.TruncateTime(a.AppDate) == e.AppDate.Date && a.AppAddress == e.AppAddress).FirstOrDefault();
                if (existApp != null)
                {
                    return new JsonResult { Data = new { status = status } };
                }
                
                if (User.IsInRole("Admin"))
                {
                    var userId = e.UID;
                    e.UID = userId;
                    e.ServiceType = ser;
                    db.Appointment.Add(e);
                }
                else
                {
                    var userId = User.Identity.GetUserId();
                    e.UID = userId;
                    e.ServiceType = ser;
                    db.Appointment.Add(e);
                }
                
            }
            db.SaveChanges();
            status = true;
            return new JsonResult { Data = new { status = status } };
        }

    }
}

Assignment/Assignment/Assignment/Controllers/ServiceTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Assignment.Models;

namespace Assignment.Controllers
{
    public class ServiceTypesController : Controller
    {
        private Model2 db = new Model2();

        // GET: ServiceTypes
        public ActionResult Index()
        {
            return View(db.ServiceType.ToList());
        }

        // GET: ServiceTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceType serviceType = db.ServiceType.Find(id);
            if (serviceType == null)
            {
                return HttpNotFound();
            }
            return View(serviceType);
        }

        // GET: ServiceTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ServiceTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TypeId,TypeName")] ServiceType serviceType)
        {
            if (ModelState.IsValid)
            {
                db.ServiceType.Add(serviceType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(serviceType);
        }

        // GET: ServiceTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceType serviceType = db.ServiceType.Find(id);
            if (serviceType == null)
            {
                return HttpNotFound();
            }
            return View(serviceType);
        }

        // POST: ServiceTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TypeId,TypeName")] ServiceType serviceType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(serviceType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(serviceType);
        }

        // GET: ServiceTypes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceType serviceType = db.ServiceType.Find(id);
            if (serviceType == null)
            {
                return HttpNotFound();
            }
            return View(serviceType);
        }

        // POST: ServiceTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ServiceType serviceType = db.ServiceType.Find(id);
            db.ServiceType.Remove(serviceType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Assignment/Assignment/Assignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("Styles",required:false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("HD House Cleaning", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Appointments", "Index", "AppointmentsAdmin")</li>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Services", "Index", "ServiceTypes")</li>
                    }

                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Overview", "Index", "AdminOverview")</li>
                    }
                    @if (User.IsInRole("User"))
                    {
                        <li>@Html.ActionLink("My Appointment", "Index", "Appointments")</li>
                    }
                    @if (User.IsInRole("User"))
                    {
                        <li>@Html.ActionLink("Calendar", "Index", "AppCalendar")</li>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Calendar", "AdminIndex", "AppCalendar")</li>
                    }


                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>